export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const SEARCH_MOVIE_DETAIL_REQUEST = 'SEARCH_MOVIE_DETAIL_REQUEST';
export const SEARCH_MOVIE_DETAIL_SUCCESS = 'SEARCH_MOVIE_DETAIL_SUCCESS';
export const SEARCH_MOVIE_DETAIL_FAILURE = 'SEARCH_MOVIE_DETAIL_FAILURE';
